apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-diamond-
spec:
  entrypoint: diamond
  templates:
  - name: sleep
    inputs:
      parameters:
      - name: message
    container:
      image: fedora:34
      command: [sleep, "10"]
  - name: diamond
    dag:
      tasks:
      - name: A
        template: sleep
      - name: B
        dependencies: [A]
        template: sleep
      - name: C
        dependencies: [A]
        template: sleep
      - name: D
        dependencies: [B, C]
        template: sleep