name: "Build workflow"
on: [push, pull_request]
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
      
      - name: Get host
        run: |
          uname -a
        shell: bash
      - name: Install k3d
        run: |
          curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | TAG=v4.0.0 bash
        shell: bash
      - name: Create k3d cluster
        run: |
          k3d cluster create
        shell: bash
      - name: Curl get kubectl
        run: |
          curl -LO https://dl.k8s.io/release/v1.21.0/bin/linux/amd64/kubectl
        shell: bash
      - name: make executable kubectl 
        run: |
          chmod +x kubectl
        shell: bash
      - name: kubectl get cluster info
        run: |
          ./kubectl cluster-info
        shell: bash