name: "Build workflow"
on: [push, pull_request]
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    container: 'fedora:34'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get hostname
        run: |
          uname -a
        shell: bash